//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_1_Portfolio.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testimonial
    {
        public int TestimonialId { get; set; }
        public string Name_Surname { get; set; }
        public string City { get; set; }
        public string Profession { get; set; }
        public Nullable<int> Balance { get; set; }
    }
}
